defmodule Etso.ModelTest do
  use ExUnit.Case
  alias __MODULE__.ModelWithoutAutogeneratedKey, as: Model
  alias __MODULE__.Repo

  setup do
    repo_id = __MODULE__
    repo_start = {Repo, :start_link, []}
    {:ok, _} = start_supervised(%{id: repo_id, start: repo_start})
    :ok
  end

  test "Fails without Primary Key" do
    assert {:error, changeset} = Model.changeset(%{}) |> Repo.insert()
    assert [primary_key: "invalid"] = changeset.errors
  end

  test "Unique Constraint" do
    assert {:ok, _} = Model.changeset(%{email: "a@example.com"}) |> Repo.insert()
    assert {:error, changeset} = Model.changeset(%{email: "a@example.com"}) |> Repo.insert()
    IO.inspect changeset
  end
end
