defmodule Etso.ModelTest.ModelWithoutAutogeneratedKey do
  use Ecto.Schema
  import Ecto.Changeset
  @primary_key {:id, :integer, autogenerate: false}

  schema "model_without_autogenerated_key" do
    field :email, :string, null: false
  end

  def changeset(params \\ %{}) do
    changeset(%__MODULE__{}, params)
    |> unique_constraint(:email)
  end

  def changeset(model, params) do
    fields = __MODULE__.__schema__(:fields)
    embeds = __MODULE__.__schema__(:embeds)
    cast_model = cast(model, params, fields -- embeds)

    Enum.reduce(embeds, cast_model, fn embed, model ->
      cast_embed(model, embed)
    end)
  end
end
